Repository sniperfactory-official/sfac-designkit-react, pull requests merged in 2023-08, with the labels that each got.

#39 Feature/badge
  app/components/Badge/Badge.tsx
  tailwind.config.js
Labels: Feature

#40 Feat:: date selector 컴포넌트 생성
  app/assets/selectArrow.svg
  app/assets/selectDate.svg
  app/components/DateSelector/DateSelector.css
  app/components/DateSelector/DateSelector.tsx
  package-lock.json
  package.json
Labels: Feature

#54 Feat:: Card 컴포넌트 제작
  app/components/Avatar/Avatar.tsx
  app/components/Card/index.tsx
  app/components/Photo/index.tsx
  app/components/Text.tsx
  app/page.tsx
  assets/photocard_default.svg
  tailwind.config.js
Labels: Feature

#42 Feat:: Searchfield component 생성
  .vscode/settings.json
  app/assets/magnifying.svg
  app/assets/magnifyingfocus.svg
  app/components/Searchfield/Searchfield.tsx
  package-lock.json
Labels: Feature

#43 Feat:: input 컴포넌트 생성
  app/components/Input/Input.tsx
Labels: Feature

#38 Feat:: textarea 컴포넌트 제작
  app/components/textarea/Textarea.tsx
Labels: Feature

#56 Feat:: Nav, Navigation Menu 컴포넌트 제작
  .eslintrc.json
  app/assets/arrow.svg
  app/assets/toggleButton.svg
  app/components/Accordion/Accordion.tsx
  app/components/Accordion/Content.tsx
  app/components/Accordion/Title.tsx
  app/components/Accordion/index.ts
  app/components/Avatar/Avatar.tsx
  app/components/Avatar/index.tsx
  app/components/Breadcrumb/Breadcrumb.tsx
  app/components/Button/Button.tsx
  app/components/Button/style.ts
  app/components/Nav/Gnb.tsx
  app/components/Nav/Navigation.tsx
  app/components/Nav/NavigationMenu.tsx
  app/components/Tab/Tab.tsx
  app/components/Text.tsx
  app/components/Title.tsx
  app/components/Toast/Toast.tsx
  assets/avatar_default.svg
  next.config.js
  package-lock.json
  package.json
  tailwind.config.js
Labels: Feature

#67 Feat:: 기본컴포넌트 배포
  README.md
  package.json
  src/Breadcrumb/index.tsx
  src/Gnb/NavigationMenu.tsx
  src/Gnb/index.tsx
  src/Layout/index.tsx
  src/Navigation/index.tsx
  src/Textarea/index.tsx
  src/index.ts
Labels: Deploy

#65 Update:: DateSelector 컴포넌트 수정
  app/components/DateSelector/DateSelector.tsx
Labels: Refactor

#74 Fix:: Avatar 컴포넌트 이미지 원형 크롭 스타일 수정
  src/Avatar/index.tsx
Labels: BugFix

#77 Feat:: Icon 컴포넌트 생성
  next.config.js
  src/Icon/index.tsx
  src/assets/icons/imgIcon/AI.svg
  src/assets/icons/imgIcon/Agree.svg
  src/assets/icons/imgIcon/All.svg
  src/assets/icons/imgIcon/AngelFace.svg
  src/assets/icons/imgIcon/App.svg
  src/assets/icons/imgIcon/Data.svg
  src/assets/icons/imgIcon/Design.svg
  src/assets/icons/imgIcon/Disagree.svg
  src/assets/icons/imgIcon/Folder.svg
  src/assets/icons/imgIcon/Game.svg
  src/assets/icons/imgIcon/Hello.svg
  src/assets/icons/imgIcon/Hit.svg
  src/assets/icons/imgIcon/Link.svg
  src/assets/icons/imgIcon/Live.svg
  src/assets/icons/imgIcon/Note.svg
  src/assets/icons/imgIcon/Security.svg
  src/assets/icons/imgIcon/Sound.svg
  src/assets/icons/imgIcon/Web.svg
  src/assets/icons/stroke/Arrow.svg
  src/assets/icons/stroke/BreadArrow.svg
  src/assets/icons/stroke/CoverBox.svg
  src/assets/icons/stroke/Quality.svg
  src/assets/icons/stroke/SkipNext.svg
  src/assets/icons/stroke/WideScreen.svg
  src/index.ts
  style.css
  webpack.config.js
Labels: Deploy

#80 Feat:: ComboBox 컴포넌트 추가 및 Icon 컴포넌트 수정
  src/ComboBox/index.tsx
  src/Icon/index.tsx
  src/assets/icons/stroke/CoverBox.svg
  src/assets/icons/stroke/Quality.svg
  src/assets/icons/stroke/SkipNext.svg
  src/assets/icons/stroke/WideScreen.svg
  src/index.ts
  style.css
Labels: Deploy

#81 Feat:: Select 컴포넌트 추가
  src/Select/index.tsx
  src/assets/check.svg
  src/assets/checked.svg
Labels: Feature

#75 Update:: Toast padding값 수정
  app/components/Toast/Toast.tsx
Labels: Style

#85 Feat:: pretendard font 추가
  src/tailwind.css
  style.css
Labels: Deploy

#87 Fix:: Card & Avatar 컴포넌트 Hotfix
  .npmignore
  src/Avatar/index.tsx
  src/Card/index.tsx
  style.css
  tailwind.config.js
Labels: BugFix

#90 Update:: Toast 컴포넌트 style 수정
  src/Icon/index.tsx
  src/Toast/index.tsx
Labels: BugFix

#92 Fix:: Live svg 파일 경로 수정
  src/Icon/index.tsx
  src/Toast/index.tsx
Labels: BugFix

#93 Fix:: Toast 컴포넌트 버튼 style 수정
  src/Toast/index.tsx
Labels: BugFix

#66 Feat:: Icon, ComboBox 컴포넌트 생성
  package-lock.json
  package.json
Labels: Feature

#69 Refactor:: Breadcrumb의 불필요한 코드 리팩토링
  app/components/Breadcrumb/Breadcrumb.tsx
Labels: Refactor
